common: &common
  host: "testing.91heba.com"
  proxy_payment:
    host: "http://wx.91heba.com"
    payment_request: "/payments/request"
  yeepay:
    yeepay_host: "http://ok.yeepay.com/"
    callbackurl: "http://wx.91heba.com/payment/yeepay/%{merchantaccount}/callback"
    fcallbackurl: "http://wx.91heba.com/payment/yeepay/%{merchantaccount}/callback"
  yeepay_api_path:
    pay_quest: "/%{api_env}/api/pay/request"
    query_order: "/%{api_env}/api/query/order"
  alipay:
    callback_url: "http://localhost:3000/payment/alipay/callback"
    notify_url: "http://localhost:3000/payment/alipay/notify"
  vip_user_pay:
    pay_quest_url: "http://localhost:3000/app/vip_user_payments/payment"
    callback_url: "http://localhost:3000/payment/vip_userpay/callback"
    notify_url: "http://localhost:3000/payment/vip_userpay/notify"

production:
  <<: *common
  proxy_payment:
    host: "http://wx.91heba.com"
    payment_request: "/payments/request"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://wx.91heba.com/payment/yeepay/%{merchantaccount}/callback"
    fcallbackurl: 'http://wx.91heba.com/payment/yeepay/%{merchantaccount}/callback'
  alipay:
    callback_url: "http://wx.91heba.com/payment/alipay/callback"
    notify_url: "http://wx.91heba.com/payment/alipay/notify"
  vip_user_pay:
    pay_quest_url: "http://wx.91heba.com/app/vip_user_payments/payment"
    callback_url: "http://wx.91heba.com/payment/vip_userpay/callback"
    notify_url: "http://wx.91heba.com/payment/vip_userpay/notify"

staging:
  <<: *common
  proxy_payment:
    host: "http://staging.91heba.com"
    payment_request: "/payments/request"
  yeepay:
    yeepay_host: "https://ok.yeepay.com/"
    callbackurl: "http://stagingm.91heba.com/payment/yeepay/%{merchantaccount}/callback"
    fcallbackurl: 'http://stagingm.91heba.com/payment/yeepay/%{merchantaccount}/callback'
  alipay:
    callback_url: "http://stagingm.91heba.com/payment/alipay/callback"
    notify_url: "http://stagingm.91heba.com/payment/alipay/notify"
  vip_user_pay:
    pay_quest_url: "http://stagingm.91heba.com/app/vip_user_payments/payment"
    callback_url: "http://stagingm.91heba.com/payment/vip_userpay/callback"
    notify_url: "http://stagingm.91heba.com/payment/vip_userpay/notify"

development:
  <<: *common
  host: "localhost:3000"
  proxy_payment:
    host: "http://wx.91heba.com"
    payment_request: "/payments/request"
  yeepay:
    yeepay_host: "http://ok.yeepay.com/"
    callbackurl: "http://localhost:3000/payment/yeepay/%{merchantaccount}/callback"
    fcallbackurl: "http://localhost:3000/payment/yeepay/%{merchantaccount}/callback"
  alipay:
    callback_url: "http://localhost:3000/payment/alipay/callback"
    notify_url: "http://localhost:3000/payment/alipay/notify"

test:
  <<: *common
